### ISSUE TITLE
how can i alter "ctrl+enter" to "ctrl+alt+enter"?

### ISSUE THREAD

**Issue by z369894** [justinfx/MayaSublime#32]
such as title...

**Comment by justinfx** [comment]
Your title leaves questions still, so please try and explain your complete request. Do you only want to define a new hotkey for the "send to Maya" command or do you want to replace (unmap) the old one as well?

Creating a new hotkey mapping is simple. Just go to your preferences and open your keymap settings for Sublime. Then enter something similar to copying the default keymap:

```json
{ 
		"keys": ["ctrl+alt+enter"], 
		"command": "send_to_maya",
		"context": [{"key": "selector", "operator": "equal", "operand": "source.python"}]
	}
```

If you also want to unmap the previous default keymap, SublimeText does not offer an official way to do this yet. But something like this has been suggested :

```json
{ "keys": "ctrl+enter"], "command": "noop" }
```

Does this solve your issue?

**Comment by m3trik** [comment]
Also just a quick idea.  I use the '[chain of command package](https://packagecontrol.io/packages/Chain%20of%20Command)' to tie a _save_  to my _send to maya_ command.  Perhaps not the behavior you want but seemed somewhat related so I thought id mention it.

**Comment by z369894** [comment]
I always use Sublime's "ctrl+enter" shortcuts, 
when I use MayaSublime, I can't use it.
so, I want to modify it.

**Comment by justinfx** [comment]
Do your custom keymap shortcut settings not override the default shortcut provided by MayaSublime? I was under the impression that if you set the key to another command that it would take precedence over defaults.
