### ISSUE TITLE
can't find keymap to change it

### ISSUE THREAD

**Issue by iansebryk** [justinfx/MayaSublime#42]
i use `ctrl+enter` and `ctrl+shift+enter` for other things.  i've tried to find the keymap command for your export function, but am unable to locate it in the sublime-keymap.  can you please point me to where you have it so i can change it?  thanks!  :)

**Comment by justinfx** [comment]
There are platform-specific keymap files right in the root of the plugin project:

- https://github.com/justinfx/MayaSublime/blob/master/Default%20(Linux).sublime-keymap
- https://github.com/justinfx/MayaSublime/blob/master/Default%20(OSX).sublime-keymap
- https://github.com/justinfx/MayaSublime/blob/master/Default%20(Windows).sublime-keymap

You can override the binding by setting the appropriate ones in your own user keybindings.

**Comment by iansebryk** [comment]
when the project is installed via Package Manager, these files (and attendant commands) aren't available; and that's where we'll look by default.  maybe make a note of that in the install notes?  it never ocurred to me to check the source repo for information that i was expecting in my install paths.

regardless, thanks for the pointer.  :)  found what i needed there.  great package, btw.  very useful!

**Comment by justinfx** [comment]
Hmm, I just tested a clean install of the MayaSublime package in SublimeText4. It creates a new entry in `Preferences -> Package Settings -> MayaSublime` as "Key Bindings - Default". That is normally where I expect to find the default key bindings and commands for installed packages, to then make my own custom bindings. What is your workflow in this case? Maybe there is some feature I am not aware of that registers the commands into another central location?

**Comment by justinfx** [comment]
Going to close this for now since it seems the original problem is fixed. Let me know if you need any other help on this.
